@echo off
rem Run this bat file as Administrator
rem 20210108en - 20210108cn

set bAutoProcessed=False

if exist "%~dp0RegHive" if exist "%~dp0binmay mingw v110615\binmay.exe" (
  reg.exe load "HKLM\TempHive" "%~dp0RegHive"
  reg.exe export "HKLM\TempHive" "%~dp0RegHive_reg.tmp"
  reg.exe unload "HKLM\TempHive"

  if exist "%~dp0RegHive_reg.tmp" (

    rem Cleaning up temporary files generated by reg.exe
    attrib -r -s -h "%~dp0*.LOG?"
    attrib -r -s -h "%~dp0*.blf"
    attrib -r -s -h "%~dp0*.regtrans-ms"
    del /f /q "%~dp0*.LOG?"
    del /f /q "%~dp0*.blf"
    del /f /q "%~dp0*.regtrans-ms"

    rem Replace "HKEY_LOCAL_MACHINE\TempHive\user\current_classes" with "HKEY_CURRENT_USER\Software\Classes"
    "%~dp0binmay mingw v110615\binmay.exe" -s "48 00 4B 00 45 00 59 00 5F 00 4C 00 4F 00 43 00 41 00 4C 00 5F 00 4D 00 41 00 43 00 48 00 49 00 4E 00 45 00 5C 00 54 00 65 00 6D 00 70 00 48 00 69 00 76 00 65 00 5C 00 75 00 73 00 65 00 72 00 5C 00 63 00 75 00 72 00 72 00 65 00 6E 00 74 00 5F 00 63 00 6C 00 61 00 73 00 73 00 65 00 73 00" -r "48 00 4B 00 45 00 59 00 5F 00 43 00 55 00 52 00 52 00 45 00 4E 00 54 00 5F 00 55 00 53 00 45 00 52 00 5C 00 53 00 6F 00 66 00 74 00 77 00 61 00 72 00 65 00 5C 00 43 00 6C 00 61 00 73 00 73 00 65 00 73 00" -i "%~dp0RegHive_reg.tmp" -o "%~dp0RegHive_reg.tmp2"

    rem Replace "HKEY_LOCAL_MACHINE\TempHive\user\current\software" with "HKEY_CURRENT_USER\Software"
    "%~dp0binmay mingw v110615\binmay.exe" -s "48 00 4B 00 45 00 59 00 5F 00 4C 00 4F 00 43 00 41 00 4C 00 5F 00 4D 00 41 00 43 00 48 00 49 00 4E 00 45 00 5C 00 54 00 65 00 6D 00 70 00 48 00 69 00 76 00 65 00 5C 00 75 00 73 00 65 00 72 00 5C 00 63 00 75 00 72 00 72 00 65 00 6E 00 74 00 5C 00 73 00 6F 00 66 00 74 00 77 00 61 00 72 00 65 00" -r "48 00 4B 00 45 00 59 00 5F 00 43 00 55 00 52 00 52 00 45 00 4E 00 54 00 5F 00 55 00 53 00 45 00 52 00 5C 00 53 00 6F 00 66 00 74 00 77 00 61 00 72 00 65 00" -i "%~dp0RegHive_reg.tmp2" -o "%~dp0RegHive_reg.tmp"

    rem Replace "HKEY_LOCAL_MACHINE\TempHive\user\current" with "HKEY_CURRENT_USER"
    "%~dp0binmay mingw v110615\binmay.exe" -s "48 00 4B 00 45 00 59 00 5F 00 4C 00 4F 00 43 00 41 00 4C 00 5F 00 4D 00 41 00 43 00 48 00 49 00 4E 00 45 00 5C 00 54 00 65 00 6D 00 70 00 48 00 69 00 76 00 65 00 5C 00 75 00 73 00 65 00 72 00 5C 00 63 00 75 00 72 00 72 00 65 00 6E 00 74 00" -r "48 00 4B 00 45 00 59 00 5F 00 43 00 55 00 52 00 52 00 45 00 4E 00 54 00 5F 00 55 00 53 00 45 00 52 00" -i "%~dp0RegHive_reg.tmp" -o "%~dp0RegHive_reg.tmp2"

    rem Replace "HKEY_LOCAL_MACHINE\TempHive\user" with "HKEY_USERS"
    "%~dp0binmay mingw v110615\binmay.exe" -s "48 00 4B 00 45 00 59 00 5F 00 4C 00 4F 00 43 00 41 00 4C 00 5F 00 4D 00 41 00 43 00 48 00 49 00 4E 00 45 00 5C 00 54 00 65 00 6D 00 70 00 48 00 69 00 76 00 65 00 5C 00 75 00 73 00 65 00 72 00" -r "48 00 4B 00 45 00 59 00 5F 00 55 00 53 00 45 00 52 00 53 00" -i "%~dp0RegHive_reg.tmp2" -o "%~dp0RegHive_reg.tmp"

    rem Replace "HKEY_LOCAL_MACHINE\TempHive\machine\software" with "HKEY_LOCAL_MACHINE\SOFTWARE"
    "%~dp0binmay mingw v110615\binmay.exe" -s "48 00 4B 00 45 00 59 00 5F 00 4C 00 4F 00 43 00 41 00 4C 00 5F 00 4D 00 41 00 43 00 48 00 49 00 4E 00 45 00 5C 00 54 00 65 00 6D 00 70 00 48 00 69 00 76 00 65 00 5C 00 6D 00 61 00 63 00 68 00 69 00 6E 00 65 00 5C 00 73 00 6F 00 66 00 74 00 77 00 61 00 72 00 65 00" -r "48 00 4B 00 45 00 59 00 5F 00 4C 00 4F 00 43 00 41 00 4C 00 5F 00 4D 00 41 00 43 00 48 00 49 00 4E 00 45 00 5C 00 53 00 4F 00 46 00 54 00 57 00 41 00 52 00 45 00" -i "%~dp0RegHive_reg.tmp" -o "%~dp0RegHive_reg.tmp2"

    rem Replace "HKEY_LOCAL_MACHINE\TempHive\machine" with "HKEY_LOCAL_MACHINE"
    "%~dp0binmay mingw v110615\binmay.exe" -s "48 00 4B 00 45 00 59 00 5F 00 4C 00 4F 00 43 00 41 00 4C 00 5F 00 4D 00 41 00 43 00 48 00 49 00 4E 00 45 00 5C 00 54 00 65 00 6D 00 70 00 48 00 69 00 76 00 65 00 5C 00 6D 00 61 00 63 00 68 00 69 00 6E 00 65 00" -r "48 00 4B 00 45 00 59 00 5F 00 4C 00 4F 00 43 00 41 00 4C 00 5F 00 4D 00 41 00 43 00 48 00 49 00 4E 00 45 00" -i "%~dp0RegHive_reg.tmp2" -o "%~dp0RegHive_reg.tmp"

    rem Delete "HKEY_LOCAL_MACHINE\TempHive\"
    "%~dp0binmay mingw v110615\binmay.exe" -s "48 00 4B 00 45 00 59 00 5F 00 4C 00 4F 00 43 00 41 00 4C 00 5F 00 4D 00 41 00 43 00 48 00 49 00 4E 00 45 00 5C 00 54 00 65 00 6D 00 70 00 48 00 69 00 76 00 65 00 5C 00" -r "" -i "%~dp0RegHive_reg.tmp" -o "%~dp0RegHive_reg.tmp2"

    rem Delete "[HKEY_LOCAL_MACHINE\TempHive]" & CRLF
    "%~dp0binmay mingw v110615\binmay.exe" -s "5B 00 48 00 4B 00 45 00 59 00 5F 00 4C 00 4F 00 43 00 41 00 4C 00 5F 00 4D 00 41 00 43 00 48 00 49 00 4E 00 45 00 5C 00 54 00 65 00 6D 00 70 00 48 00 69 00 76 00 65 00 5D 00 0D 00 0A 00" -r "" -i "%~dp0RegHive_reg.tmp2" -o "%~dp0RegHive_reg.txt"

    rem Cleaning up temporary file
    del /f /q "%~dp0RegHive_reg.tmp"
    del /f /q "%~dp0RegHive_reg.tmp2"

    set bAutoProcessed=True

  )
)


echo.
if "%bAutoProcessed%"=="True" if exist "%~dp0RegHive_reg.txt" (
  echo [DONE!] reg file saved in this path:
  echo %~dp0RegHive_reg.txt
  echo.
)
echo.
echo Press any key to exit...
pause>nul
exit
